### PR TITLE
Change "thermal" to "heat" (in most places)

### PR DESCRIPTION
**Pull request by glwagner**
After a bit of rumination I think we should use the term "heat flux" not "thermal flux". It's more standard. Sorry for any pain this causes...

@jlk9

### CODE REVIEW

**Comment by jlk9** [comment]
You need to change the directory and file names from "Thermal" to "Heat" too, in "ThermalBoundaryConditions" at least

**Comment by glwagner** [comment]
> You need to change the directory and file names from "Thermal" to "Heat" too, in "ThermalBoundaryConditions" at least

thank you!

**Review by jlk9 — COMMENTED** [review]
Did you want to change the name of IceWaterThermalEquilibrium as well?

**Comment by glwagner** [comment]
> Did you want to change the name of IceWaterThermalEquilibrium as well?

I thought "thermal equilibrium" made sense to keep since that's the typical expression. For fluxes though we usually say "heat flux" not "thermal flux", that motivates the changes we've put in so far. What do you think?

**Comment by glwagner** [comment]
For example

https://en.wikipedia.org/wiki/Thermal_equilibrium

but

https://en.wikipedia.org/wiki/Heat_equation

**Comment by jlk9** [comment]
I agree, that's how I've usually heard fluxes / equilibrium referred to as well, just wanted to make sure.

**Review by jlk9 — APPROVED** [review]

**Comment by glwagner** [comment]
great!

**Pull request merged**
