### PR TITLE
bump oceananigans compat

### PR DESCRIPTION
**Pull request by wsmoses**
## Purpose 
<!--- One sentence to describe the purpose of this PR, refer to any linked issues:

bump oceananigans compat

### CODE REVIEW

**Comment by wsmoses** [comment]
@glwagner

**Review by navidcy — APPROVED** [review]
lgtm

but the docs build fails -- is it related to this?

btw, the Manifest probably still has the 0.90.x version

**Comment by wsmoses** [comment]
yeah looks like the example fails for reasons beyond my understanding. 

Feel free to take over the PR, I've hit allow edits by maintainers.

**Comment by navidcy** [comment]
Was the example OK before the PR?

**Comment by glwagner** [comment]
The failure clearly has nothing to do with this PR so it was probably broken already

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
Thanks @wsmoses

**Pull request merged**
